SELECT "Año" AS "Año",
	"cedula" AS "Documento_identidad",
	"Modalidad" AS "Modalidad",
	"Facultad" AS "Facultad",
	"Tipo_de_Formacion" AS "Tipo_Formacion",
	"Programa" AS "Programa",
	"ACA1" AS "Plan de estudios de tu programa",
	"ACA2" AS "Pertinencia de los conocimientos adquiridos en las clases",
	"ACA3" AS "Contribución del programa en tu proceso formativo",
	"ACA4" AS "¿¿Qué tan cumplida ha sido la promesa de valor académica ofrecida?",
	"ACA5" AS "Conforme al avance de tu programa académico:",
	"ACA6" AS "Conocimiento disciplinar",
	"ACA7" AS "Competencias para la enseñanza y la formación",
	"ACA8" AS "Cumplimiento del syllabus y plan de estudios del programa",
	"ACA9" AS "Evaluación y acompañamiento del proceso de aprendizaje",
	"ACA10" AS "Entrega de calificaciones y retroalimentación",
	"ACA11" AS "Calidad humana",
	"ACA12" AS "Compromiso",
	"ACA13" AS "Manejo tecnológico",
	"ACA14" AS "Decano(a)",
	"ACA15" AS "Director(a) de Programa o Coordinador",
	"ACA16" AS "Satisfacción entrega material VAC",
	"ACA17" AS "Satisfacción asistentes facultad",
	"ACA18" AS "Probabilidad recomendar programa académico",
	"ACA19" AS "Probabilidad volver a estudiar en EAN",
	"ACA20" AS "Cuerpo docente con experiencia profesional"
FROM "01_LT_AWS_ENCUSATIS2024_02"
UNION ALL
SELECT "Id_2023" AS "Año",
	"Para iniciar, por favor indícanos el número de tu documento de identidad:" AS "Documento_identidad",
	"Modalidad" AS "Modalidad",
	NULL AS "Facultad",
	NULL AS "Tipo_Formacion",
	"Programa" AS "Programa",
	"ACA1" AS "Plan de estudios de tu programa",
	"ACA2" AS "Pertinencia de los conocimientos adquiridos en las clases",
	"ACA3" AS "Contribución del programa en tu proceso formativo",
	"ACA4" AS "¿¿Qué tan cumplida ha sido la promesa de valor académica ofrecida?",
	"ACA5" AS "Conforme al avance de tu programa académico:",
	"ACA6" AS "Conocimiento disciplinar",
	"ACA7" AS "Competencias para la enseñanza y la formación",
	"ACA8" AS "Cumplimiento del syllabus y plan de estudios del programa",
	"ACA9" AS "Evaluación y acompañamiento del proceso de aprendizaje",
	"ACA10" AS "Entrega de calificaciones y retroalimentación",
	"ACA11" AS "Calidad humana",
	"ACA12" AS "Compromiso",
	"ACA13" AS "Manejo tecnológico",
	"ACA14" AS "Decano(a)",
	"ACA15" AS "Director(a) de Programa o Coordinador",
	"ACA17" AS "Satisfacción entrega material VAC",
	"ACA18" AS "Satisfacción asistentes facultad",
	"ACA29" AS "Probabilidad recomendar programa académico",
	"ACA30" AS "Probabilidad volver a estudiar en EAN",
	NULL AS "Cuerpo docente con experiencia profesional"
FROM "01_LT_AWS_ENCUSATIS2023_01"
UNION ALL
SELECT "Año" AS "Año",
	"Cedula" AS "Documento_identidad",
	"Metododologia" AS "Metododologia",
	"Facultad" AS "Facultad",
	NULL AS "Tipo_Formacion",
	"Programa" AS "Programa",
	"AC1" AS "Plan de estudios de tu programa",
	NULL AS "Pertinencia de los conocimientos adquiridos en las clases",
	NULL AS "Contribución del programa en tu proceso formativo",
	"AC3" AS "¿¿Qué tan cumplida ha sido la promesa de valor académica ofrecida?",
	NULL AS "Conforme al avance de tu programa académico:",
	"AC4" AS "Conocimiento disciplinar",
	"AC5" AS "Competencias para la ensenanza y la formacion",
	"AC6" AS "Cumplimiento del Syllabus y plan de estudios del programa",
	"AC7" AS "Evaluacion y acompanamiento del proceso de aprendizaje",
	"AC8" AS "Entrega de calificaciones y retroalimentación",
	NULL AS "Calidad humana",
	NULL AS "Compromiso",
	NULL AS "Manejo tecnológico",
	"AC9" AS "Decano",
	"AC10" AS "Director(a) de Programa o Coordinador",
	"AC12" AS "En general ¿Que tan satisfecho te encuentras con la atencion y el servicio recibido  del equipo de la Unidad Academico Administrativa",
	"AC13" AS "En general ¿Que tan satisfecho te encuentras con la atencion y el servicio recibido por parte de los asistentes de tu Facultad",
	"AC15" AS "¿Que tan probable es que recomiendes tu programa academico con familiares y amigos",
	"AC16" AS "¿Que tan probable es que en el futuro vuelvas a estudiar un programa academico en la Universidad Ean",
	NULL AS "Cuerpo docente con experiencia profesional"
FROM "01_LT_AWS_ENCUSATIS2022_01"
UNION ALL
SELECT "ID_2021" AS "Año",
	"CC" AS "Documento_identidad",
	"Metodologia " AS "Metodologia ",
	NULL AS "Facultad",
	NULL AS "Tipo_Formacion",
	"Programa " AS "Programa ",
	"AC1" AS "Plan de estudios de tu programa",
	NULL AS "Pertinencia de los conocimientos adquiridos en las clases",
	NULL AS "Contribución del programa en tu proceso formativo",
	"AC3" AS "¿¿Qué tan cumplida ha sido la promesa de valor académica ofrecida?",
	NULL AS "Conforme al avance de tu programa académico:",
	"AC4" AS "Conocimiento disciplinar",
	"AC5" AS "Competencias para la ensenanza y la formacion",
	"AC6" AS "Cumplimiento del Syllabus y plan de estudios del programa",
	"AC7" AS "Evaluación y acompañamiento del proceso de aprendizaje",
	"AC8" AS "Entrega de calificaciones y retroalimentación",
	NULL AS "Calidad humana",
	NULL AS "Compromiso",
	NULL AS "Manejo tecnológico",
	"AC9" AS "Decano",
	"AC10" AS "Director(a) de Programa o Coordinador",
	"AC11" AS "En general ¿Que tan satisfecho te encuentras con la atencion y el servicio recibido  del equipo de la Unidad Academico Administrativa",
	"AC12" AS "En general ¿Que tan satisfecho te encuentras con la atencion y el servicio recibido por parte de los asistentes de tu Facultad",
	"AC15" AS "¿Que tan probable es que recomiendes tu programa academico con familiares y amigos",
	"AC16" AS "¿Que tan probable es que en el futuro vuelvas a estudiar un programa academico en la Universidad Ean",
	NULL AS "Cuerpo docente con experiencia profesional"
FROM "01_LT_AWS_ENCUSATIS2021_01"
UNION ALL
SELECT "Year" AS "Año",
	"Cedula" AS "Documento_identidad",
	NULL AS "Metodologia ",
	NULL AS "Facultad",
	NULL AS "Tipo_Formacion",
	NULL AS "Programa ",
	"AC1" AS "Plan de estudios de tu programa",
	NULL AS "Pertinencia de los conocimientos adquiridos en las clases",
	NULL AS "Contribución del programa en tu proceso formativo",
	"AC2" AS "¿¿Qué tan cumplida ha sido la promesa de valor académica ofrecida?",
	NULL AS "Conforme al avance de tu programa académico:",
	NULL AS "Conocimiento disciplinar",
	NULL AS "Competencias para la ensenanza y la formacion",
	NULL AS "Cumplimiento del Syllabus y plan de estudios del programa",
	NULL AS "Evaluacion y acompanamiento del proceso de aprendizaje",
	"AC4" AS "Entrega de calificaciones y retroalimentación",
	NULL AS "Calidad humana",
	NULL AS "Compromiso",
	"AC8" AS "Manejo tecnológico",
	NULL AS "Decano",
	NULL AS "Director(a) de Programa o Coordinador",
	"AC7" AS "En general ¿Que tan satisfecho te encuentras con la atencion y el servicio recibido  del equipo de la Unidad Academico Administrativa",
	"AC6" AS "En general ¿Que tan satisfecho te encuentras con la atencion y el servicio recibido por parte de los asistentes de tu Facultad",
	NULL AS "¿Que tan probable es que recomiendes tu programa academico con familiares y amigos",
	"AC10" AS "¿Que tan probable es que en el futuro vuelvas a estudiar un programa academico en la Universidad Ean",
	NULL AS "Cuerpo docente con experiencia profesional"
FROM "01_LT_AWS_ENCUSATIS2020_01"
UNION ALL
SELECT "ID_2019" AS "Año",
	NULL AS "Documento_identidad",
	"Modalidad" AS "Metododologia",
	NULL AS "Facultad",
	NULL AS "Tipo_Formacion",
	NULL AS "Programa",
	"AC1" AS "Plan de estudios de tu programa",
	NULL AS "Pertinencia de los conocimientos adquiridos en las clases",
	NULL AS "Contribución del programa en tu proceso formativo",
	"AC9" AS "¿¿Qué tan cumplida ha sido la promesa de valor académica ofrecida?",
	NULL AS "Conforme al avance de tu programa académico:",
	NULL AS "Conocimiento disciplinar",
	"AC2" AS "Competencias para la enseñanza y la formación",
	NULL AS "Cumplimiento del syllabus y plan de estudios del programa",
	"AC4" AS "Evaluación y acompañamiento del proceso de aprendizaje",
	"AC5" AS "Entrega de calificaciones y retroalimentación",
	"AC3" AS "Calidad humana",
	NULL AS "Compromiso",
	NULL AS "Manejo tecnológico",
	NULL AS "Decano",
	"AC7" AS "Director(a) de Programa o Coordinador",
	"AC10" AS "En general ¿Que tan satisfecho te encuentras con la atencion y el servicio recibido  del equipo de la Unidad Academico Administrativa",
	"AC8" AS "En general ¿Que tan satisfecho te encuentras con la atencion y el servicio recibido por parte de los asistentes de tu Facultad",
	"AC11" AS "¿Que tan probable es que recomiendes tu programa academico con familiares y amigos",
	NULL AS "¿Que tan probable es que en el futuro vuelvas a estudiar un programa academico en la Universidad Ean",
	NULL AS "Cuerpo docente con experiencia profesional"
FROM "01_LT_AWS_ENCUSATIS2019_01"